### ISSUE TITLE
Bug 1.3: Windows install failed

### ISSUE THREAD

**Issue by ibex-are-goats** [6c65726f79/Transmissionic#272] opened 2021-06-14 05:53 UTC
Error: https://i.imgur.com/ThciXNY.png

Thank you for working on this app!

**Comment by 6c65726f79** [comment] 2021-06-14 10:31
Thank you for reporting this bug, unfortunatly I can't reproduce it on my side. Is it the first time you install the app ? And have you tried to relaunch the app ? This bug seems to occur randomly.

**Comment by ibex-are-goats** [comment] 2021-06-14 11:34
App seems to run fine after the error. First time installing. Happy to report so you know about it. No sweat!

**Comment by 6c65726f79** [comment] 2021-06-19 12:51
Bug fixed in the final [1.3.0](https://github.com/6c65726f79/Transmissionic/releases/tag/v1.3.0) version.

**Closed by 6c65726f79** 2021-06-19 12:51 UTC
Labels: bug, question

**Comment by ibex-are-goats** [comment] 2021-06-19 13:01
Well done! Keep up the good work!
